// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7SRHX4Osb6Abp0Jpq9HHvJySL_cKqftY',
    appId: '1:514946265261:web:b2491f0b5f71a9d86c1624',
    messagingSenderId: '514946265261',
    projectId: 'fir-finalproject-587df',
    authDomain: 'fir-finalproject-587df.firebaseapp.com',
    storageBucket: 'fir-finalproject-587df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcgecYax24bMr-BBOm2u20EdCwISpt5ls',
    appId: '1:514946265261:android:a05e6d53b237e7e36c1624',
    messagingSenderId: '514946265261',
    projectId: 'fir-finalproject-587df',
    storageBucket: 'fir-finalproject-587df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6_1kgaOKP1GhrncuwBqk8dr_Ndde9Amg',
    appId: '1:514946265261:ios:8d16d97881fa87436c1624',
    messagingSenderId: '514946265261',
    projectId: 'fir-finalproject-587df',
    storageBucket: 'fir-finalproject-587df.appspot.com',
    iosClientId: '514946265261-jkl3k3bacnrqlj52vaef2vjinbgbasn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyekambw',
  );
}
